# Generated by Django 3.1.4 on 2023-10-31 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erabiltzailea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('abizena1', models.CharField(max_length=100)),
                ('abizena2', models.CharField(max_length=100)),
                ('nan', models.CharField(max_length=9)),
                ('helbideElektronikoa', models.EmailField(max_length=100)),
                ('pasahitza', models.CharField(max_length=250)),
                ('perfil', models.IntegerField(default=1, max_length=1)),
                ('sortua', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Helbidea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herria', models.CharField(max_length=100)),
                ('kodigoPostala', models.CharField(max_length=100)),
                ('kalea', models.CharField(max_length=250)),
                ('zenbakiaPisua', models.CharField(max_length=250)),
                ('datuExtra', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produktua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izena', models.CharField(max_length=100)),
                ('deskripzioa', models.CharField(max_length=500)),
                ('argazkia', models.CharField(max_length=500)),
                ('prezioa', models.IntegerField(max_length=9)),
                ('stock', models.IntegerField(max_length=9)),
                ('pisua', models.IntegerField(max_length=9)),
                ('vip', models.IntegerField(default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Saskia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kantitatea', models.IntegerField(max_length=2)),
                ('zenbakia', models.IntegerField(max_length=3)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.erabiltzailea')),
                ('produktua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.produktua')),
            ],
        ),
        migrations.CreateModel(
            name='Salmenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zenbakiaSaskia', models.IntegerField(max_length=3)),
                ('prezioaFinala', models.IntegerField(max_length=9)),
                ('data', models.DateField(auto_now=True)),
                ('erabiltzailea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.erabiltzailea')),
            ],
        ),
        migrations.AddField(
            model_name='erabiltzailea',
            name='helbidea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.helbidea'),
        ),
    ]
