# Generated by Django 3.1.4 on 2023-11-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20231103_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabiltzailea',
            name='helbidea',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='web.helbidea'),
        ),
    ]
