# Generated by Django 3.1.4 on 2023-11-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20231103_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erabiltzailea',
            name='helbidea',
            field=models.CharField(max_length=1500),
        ),
        migrations.DeleteModel(
            name='Helbidea',
        ),
    ]
