# Generated by Django 3.1.4 on 2023-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20231103_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erabiltzailea',
            name='helbidea',
        ),
        migrations.AddField(
            model_name='salmenta',
            name='helbidea',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
