# Generated by Django 3.1.4 on 2023-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20231103_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produktua',
            name='argazkia',
            field=models.FilePathField(path='/../static/img'),
        ),
    ]
