# Generated by Django 3.1.4 on 2023-11-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20231107_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='produktua',
            name='kategoria',
            field=models.CharField(default='', max_length=100),
        ),
    ]
