# Generated by Django 3.1.4 on 2023-11-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_produktua_kategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='saskia',
            name='bukatuta',
            field=models.IntegerField(default=0),
        ),
    ]
