# Generated by Django 3.1.4 on 2023-11-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20231107_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saskia',
            name='kantitatea',
            field=models.IntegerField(null=True),
        ),
    ]
