# Generated by Django 3.1.4 on 2023-11-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_deskontua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salmenta',
            name='prezioaFinala',
            field=models.CharField(max_length=100),
        ),
    ]
